name: Coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: [ CPU ]
    steps:
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/index.html
        run: npm run code-coverage

