name: Coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: [ CPU ]
    steps:
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./index.html
        run: 
          wget -q https://xly.bce.baidu.com/ipipe/ipipe-report/report/27877949/c++-coverage/tensorrt/index.html
          ls
          npm run code-coverage

