FRAME = ['hong19860320', 'lijianshe02', 'wangchaochaohu', 'Superjomn', 'wzzju', 'luotao1', 'liuwei1031', 'ysh329', 'Xreki', 'wangchaochaohu', 'NHZlX', 'zhhsplendid', 'zhupengyang', 'phlrain', 'fc500110', 'chenwhql', 'FrostML', 'tianshuo78520a', 'Shixiaowei02', 'zhouwei25', 'gfwm2013', 'juncaipeng', 'liym27', 'zhangting2020', 'cyj1986', 'yongqiangma', 'zhiqiu', 'jiweibo', 'DannyIsFunny', 'cryoco', 'GaoWei8', 'raindrops2sea', 'T8T9', 'iducn3@163.com', 'lelelelelez', 'qili93', 'randytli', 'pangyoki', 'feng626']
MODEL = ['guoshengCS', 'jerrywgz','lanxianghit', 'FDInSky', 'heavengate', 'Aurelius84', 'shippingwang', 'ruri', 'SunGaofeng', 'still-wait', 'x', 'ceci3', 'baiyfbupt', '0YuanZhang0', 'LielinJiang', 'kuke', 'wanghaoshuang', 'XiaoguangHu01', 'tink2123', 'huangjun12', 'qingqing01', '0ZhangYuan0', 'iclementine', 'xinyu009', 'xixiaoyao', 'lfchener', 'slf12', 'LDOUBLEV', 'willthefrog', 'vincentXiyu', 'wangxiao1021', 'dyning', 'littletomatodonkey', 'chajchaj', 'MissPenguin', 'FrostML', 'joejiong', 'yukavio', 'wqz960', 'LiuChiachi']
DIST = ['seiriosPlus', 'frankwhzhang', 'zhangwenhui03', 'wangjiawei04', 'guru4elephant', 'gongweibao', 'hutuxian', 'sandyhouse', 'xjqbest', 'yaoxuefeng6', 'gavin1332', 'fuyinno4', 'wangxicoding', 'qjing666', 'mapingshuo', 'ForFishes', 'danleifeng', 'MrChengmo', '123malin', 'Thunderbrook', 'wilhelmzh', 'vslyu']
CLOUD = ['ScoThunder', 'houj04', 'SnailSword', 'jiaqianjing', 'ifkite', 'yangql176', 'xymyeah', 'yxfGrace']
TOOL = ['ZeyuChen', 'jiangjiajun', 'Steffy-zxf', 'SunAhong1993', 'FlyingQianMM', 'wawltor', 'mamingjie-China', 'nepeplwu', 'kinghuin', 'ZHUI', 'LutaoChu', 'wuyefeilin']
QA = ['kolinwei', 'zhengya01', 'xiegegege', 'OliverLPH', 'JiaXiao243', 'gentelyang', 'DDDivano', 'ccmeteorljh', 'chalsliu', 'gzydsmz', 'mmglove', 'hysunflower', 'zjjhxpy', 'XieYunshen']
PM = ['AIpioneer', 'adaxi123', 'niuchaopku', 'grasswolfs']
TPM = ['saxon-zh', 'swtkiwi', 'Heeenrrry', 'jzhang533', 'TCChenlong', 'dingjiaweiww', 'liuTINA0907']

DIMISSION = ['liuwei1031', 'tensor-tang', 'sneaxiy', 'zhaoyuchen2018', 'songyouwei', 'zoooooooyuan', 'cuichaowen', 'silingtong123', 'JepsonWong', 'zhongpu', 'wopeizl', 'peizhilin', 'chengduoZH', 'JiabinYang', 'junjun315', 'xyoungli', 'DogHeadMoon', 'throneclay', 'bdzhuxiaoning', 'luluxing3', 'xyzhou-puck', 'jesseyxujin', 'xinyu009', 'wangguibao', 'jacquesqiao', 'renhaosw', 'CandyCaneLane', 'drmfsls', 'yuanfanglin', 'kh2se2013', 'xiaosang', 'ZhangRui-github', 'baomengxue', 'fyl9409', 'yyyizhi', 'Boyan-Liu']
#不加离职同学 （2020. 7.20）
#PADDLE_DEPART = ['hong19860320', 'jerrywgz', 'lijianshe02', 'wangchaochaohu', 'Superjomn', 'wzzju', 'luotao1', 'liuwei1031', 'ysh329', 'Xreki', 'wangchaochaohu', 'NHZlX', 'zhhsplendid', 'zhupengyang', 'phlrain', 'fc500110', 'chenwhql', 'FrostML', 'tianshuo78520a', 'Shixiaowei02', 'zhouwei25', 'gfwm2013', 'juncaipeng', 'liym27', 'zhangting2020', 'cyj1986', 'yongqiangma', 'zhiqiu', 'jiweibo', 'DannyIsFunny', 'cryoco', 'GaoWei8', 'raindrops2sea', 'T8T9', 'iducn3@163.com', 'lelelelelez', 'qili93', 'randytli', 'pangyoki', 'feng626', 'guoshengCS', 'lanxianghit', 'FDInSky', 'heavengate', 'Aurelius84', 'shippingwang', 'ruri', 'SunGaofeng', 'still-wait', 'x', 'ceci3', 'baiyfbupt', '0YuanZhang0', 'LielinJiang', 'kuke', 'wanghaoshuang', 'XiaoguangHu01', 'tink2123', 'huangjun12', 'qingqing01', '0ZhangYuan0', 'iclementine', 'xinyu009', 'xixiaoyao', 'lfchener', 'slf12', 'LDOUBLEV', 'willthefrog', 'vincentXiyu', 'wangxiao1021', 'dyning', 'littletomatodonkey', 'chajchaj', 'MissPenguin', 'FrostML', 'joejiong', 'yukavio', 'wqz960', 'LiuChiachi', 'seiriosPlus', 'frankwhzhang', 'zhangwenhui03', 'wangjiawei04', 'guru4elephant', 'gongweibao', 'hutuxian', 'sandyhouse', 'xjqbest', 'yaoxuefeng6', 'gavin1332', 'fuyinno4', 'wangxicoding', 'qjing666', 'mapingshuo', 'ForFishes', 'danleifeng', 'MrChengmo', '123malin', 'Thunderbrook', 'wilhelmzh', 'vslyu', 'ScoThunder', 'houj04', 'SnailSword', 'jiaqianjing', 'ifkite', 'yangql176', 'xymyeah', 'yxfGrace', 'ZeyuChen', 'jiangjiajun', 'Steffy-zxf', 'SunAhong1993', 'FlyingQianMM', 'wawltor', 'mamingjie-China', 'nepeplwu', 'kinghuin', 'ZHUI', 'LutaoChu', 'wuyefeilin', 'kolinwei', 'zhengya01', 'xiegegege', 'OliverLPH', 'JiaXiao243', 'gentelyang', 'DDDivano', 'ccmeteorljh', 'chalsliu', 'gzydsmz', 'mmglove', 'hysunflower', 'zjjhxpy', 'XieYunshen', 'AIpioneer', 'adaxi123', 'niuchaopku', 'grasswolfs', 'saxon-zh', 'swtkiwi', 'Heeenrrry', 'jzhang533', 'TCChenlong', 'dingjiaweiww', 'liuTINA0907']
#加入离职同学
PADDLE_DEPART = ['hong19860320', 'jerrywgz', 'lijianshe02', 'wangchaochaohu', 'Superjomn', 'wzzju', 'luotao1', 'liuwei1031', 'ysh329', 'Xreki', 'wangchaochaohu', 'NHZlX', 'zhhsplendid', 'zhupengyang', 'phlrain', 'fc500110', 'chenwhql', 'FrostML', 'tianshuo78520a', 'Shixiaowei02', 'zhouwei25', 'gfwm2013', 'juncaipeng', 'liym27', 'zhangting2020', 'cyj1986', 'yongqiangma', 'zhiqiu', 'jiweibo', 'DannyIsFunny', 'cryoco', 'GaoWei8', 'raindrops2sea', 'T8T9', 'iducn3@163.com', 'lelelelelez', 'qili93', 'randytli', 'pangyoki','feng626', 'guoshengCS', 'lanxianghit', 'FDInSky', 'heavengate', 'Aurelius84', 'shippingwang', 'ruri', 'SunGaofeng', 'still-wait', 'x', 'ceci3', 'baiyfbupt', '0YuanZhang0', 'LielinJiang', 'kuke', 'wanghaoshuang', 'XiaoguangHu01', 'tink2123', 'huangjun12', 'qingqing01', '0ZhangYuan0', 'iclementine', 'xinyu009', 'xixiaoyao', 'lfchener', 'slf12', 'LDOUBLEV', 'willthefrog', 'vincentXiyu', 'wangxiao1021', 'dyning', 'littletomatodonkey', 'chajchaj', 'MissPenguin', 'FrostML', 'joejiong', 'yukavio', 'wqz960', 'LiuChiachi', 'seiriosPlus', 'frankwhzhang', 'zhangwenhui03', 'wangjiawei04', 'guru4elephant', 'gongweibao', 'hutuxian', 'sandyhouse', 'xjqbest', 'yaoxuefeng6', 'gavin1332', 'fuyinno4', 'wangxicoding', 'qjing666', 'mapingshuo', 'ForFishes', 'danleifeng', 'MrChengmo', '123malin', 'Thunderbrook', 'wilhelmzh', 'vslyu', 'ScoThunder', 'houj04', 'SnailSword', 'jiaqianjing', 'ifkite', 'yangql176', 'xymyeah', 'yxfGrace', 'ZeyuChen', 'jiangjiajun', 'Steffy-zxf', 'SunAhong1993', 'FlyingQianMM', 'wawltor', 'mamingjie-China', 'nepeplwu', 'kinghuin', 'ZHUI', 'LutaoChu', 'wuyefeilin', 'kolinwei', 'zhengya01', 'xiegegege', 'OliverLPH', 'JiaXiao243', 'gentelyang', 'DDDivano', 'ccmeteorljh', 'chalsliu', 'gzydsmz', 'mmglove', 'hysunflower', 'zjjhxpy', 'XieYunshen', 'AIpioneer', 'adaxi123', 'niuchaopku', 'grasswolfs', 'saxon-zh', 'swtkiwi', 'Heeenrrry', 'jzhang533', 'TCChenlong', 'dingjiaweiww', 'liuTINA0907', 'liuwei1031', 'tensor-tang', 'sneaxiy', 'zhaoyuchen2018', 'songyouwei', 'zoooooooyuan', 'cuichaowen', 'silingtong123', 'JepsonWong', 'zhongpu', 'wopeizl', 'peizhilin', 'chengduoZH', 'JiabinYang', 'junjun315', 'xyoungli', 'DogHeadMoon', 'throneclay', 'bdzhuxiaoning', 'luluxing3', 'xyzhou-puck', 'jesseyxujin', 'xinyu009', 'wangguibao', 'jacquesqiao', 'renhaosw', 'CandyCaneLane', 'drmfsls', 'yuanfanglin', 'kh2se2013', 'xiaosang', 'ZhangRui-github', 'baomengxue', 'fyl9409', 'yyyizhi', 'Boyan-Liu', 'cs2be', 'sabreshao', 'xuezhong', 'xsrobin', 'yihuaxu', 'chenjiaoangel', 'channingss', 'wanghuancoder', 'huangxu96', 'meiyim', 'gfwm0502']

OTHER_DEPART = ['wutianyiRosun', 'anpark', 'kgresearch', 'zhhezhhe', 'parap1uie-s', 'yuan19940121@163.com', 'sserdoubleh', 'AndyELiu', 'HongyuLi2018', 'kahitomi', 'imguozhen', 'AoZhang', 'qingshuchen', 'parap1uie-s', 'jshower', 'yipeng-sun', 'liuhuicnn']
INTEL = ['abhinavarora', 'grygielski', 'jczaja', 'kbinias', 'lidanqing-intel', 'pzelazko-intel', 'pawelpiotrowicz', 'Sand3r-', 'sfraczek', 'tpatejko', 'wojtuss', 'wozna', 'mozga-intel']
NOT_KONW = ['backyes', 'beckett1124', 'chengxiaohua1105', 'zhouxiao-coder', 'cxwangyi', 'yiwangbaidu', 'wangkuiyi', 'cxysteven', 'dzhwinter', 'dragonwarrior', 'emailweixu', 'gangliao', 'Haichao-Zhang', 'hedaoyuan', 'helinwang', 'JiayiFeng', 'kexinzhao', 'lcy-seso', 'cjld', 'lipeng-unisound', 'liuyuan', 'livc', 'llxxxll', 'lzhao4ever', 'Noplz', 'pakchoi', 'panyx0718', 'pengli09', 'pkuyym', 'QiJune', 'reyoung', 'tianbingsz', 'typhoonzero', 'velconia', 'wangyang59', 'wangzhen-nlp', 'wen-bo-yang', 'wwhu', 'xinghai-sun', 'xujun05', 'xushaoyong', 'Yancey1989', 'zhaopu7', 'zhouxiao-coder', 'Zrachel']
#Guo Sheng
